# controller_manager provides the necessary infrastructure to manage multiple controllers
# efficiently and robustly using ROS 2 Control.
controller_manager:
 ros__parameters:
   update_rate: 50  # Hz

   # Declare the controllers
   joint_state_broadcaster:
     type: joint_state_broadcaster/JointStateBroadcaster

   diff_drive_controller:
     type: diff_drive_controller/DiffDriveController

# Parameters for the diff drive controller
diff_drive_controller:
 ros__parameters:
   # Joints
   left_wheel_names: ["${prefix}front_left_wheel_joint", "${prefix}back_left_wheel_joint"]
   right_wheel_names: ["${prefix}front_right_wheel_joint", "${prefix}back_right_wheel_joint"]

   # Robot physical parameters
   wheel_separation: 0.169
   wheel_radius: 0.0325

   # TF configuration
   odom_frame_id: odom
   base_frame_id: base_link

   # Odometry parameters
   pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
   twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
   enable_odom_tf: true

   # Command handling
   cmd_vel_timeout: 0.5
   publish_limited_velocity: false
   velocity_rolling_window_size: 10
   publish_rate: 50.0

   # Velocity limits
   linear.x.has_velocity_limits: false
   linear.x.has_acceleration_limits: false
   linear.x.has_jerk_limits: false
   linear.x.max_velocity: 0.0
   linear.x.min_velocity: 0.0
   linear.x.max_acceleration: 0.0
   linear.x.max_jerk: 0.0
   linear.x.min_jerk: 0.0
   angular.z.has_velocity_limits: false
   angular.z.has_acceleration_limits: false
   angular.z.has_jerk_limits: false
   angular.z.max_velocity: 0.0
   angular.z.min_velocity: 0.0
   angular.z.max_acceleration: 0.0
   angular.z.min_acceleration: 0.0
   angular.z.max_jerk: 0.0
   angular.z.min_jerk: 0.0

